[package]
name = "bookmark-server"
version = "0.1.0"
authors = ["koehr <n@koehr.in>"]

[dependencies]
uuid = { version = "0.5", features = ["v4"] }
rocket = "0.3"
rocket_codegen = "0.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
